### ISSUE TITLE
connecting calendar with backend

### ISSUE THREAD

**Issue by sophiepopow** [ProductivityPal/frontend#31]
```[tasklist]
### Tasks
- [ ] changing LocalDate to LocalDateTime
- [x] Adding new task to calendar request
- [ ] Updating task dateTime in calendar request
```
