### ISSUE TITLE
CurrentTaskPanel

### ISSUE THREAD

**Issue by sophiepopow** [ProductivityPal/frontend#52]
```[tasklist]
### Tasks
- [x] Filtering out passed events
- [x] Fix Filtering bug
- [x] Finding current event
- [x] Adding endTime to tasks
- [x] Fixing min estimation time
- [x] Displaing current Task in a panel
- [ ] https://github.com/ProductivityPal/frontend/issues/59
- [ ] https://github.com/ProductivityPal/frontend/issues/60
- [x] Not displaying panel if there is no current task
```
